version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: vulnerability_triage_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: vulnerability_triage
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - vulnerability_triage_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/vulnerability_triage --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongo-express:
    image: mongo-express:1.0.0
    container_name: vulnerability_triage_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - vulnerability_triage_network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  vulnerability_triage_network:
    driver: bridge